name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - run: yarn install --immutable

      - name: Type check
        run: yarn tsc:full

      - name: Lint
        run: yarn lint

      - name: Format check
        run: yarn format:check

      - name: Test
        run: yarn test
